name: Deploy to Render

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./monolith
          file: ./monolith/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/dantulootravels:latest

      - name: Deploy to Render
        run: |
          curl -X POST \
            -H "Accept: application/json" \
            -H "Content-Type: application/json" \
            -d '{"clearCache": false}' \
            https://api.render.com/deploy/srv-cq3in03qf0us73diihe0?key=UTlDQ1yo06A
